name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Lua
      uses: leafo/gh-actions-lua@v11
      with:
        luaVersion: "5.1.5"
    
    - name: Install busted and luassert
      run: |
        sudo apt-get update
        sudo apt-get install -y luarocks
        luarocks install busted
        luarocks install luassert
    
    - name: Run tests
      run: |
        cd $GITHUB_WORKSPACE
        bash test/run_tests.sh
